apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloservice
  namespace: aa-team
spec:
  selector:
    matchLabels:
      app: helloservice
  template:
    metadata:
      labels:
        app: helloservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: docker.io/saiyam911/ossjapan:sha-9319ddf
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: helloservice
  namespace: aa-team
spec:
  selector:
    app: helloservice
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: NodePort
  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
  name: demo-app-ingress
  namespace: aa-team
spec:
  rules:
  - host: demo.e65f444e-e201-40bd-b0f4-7a18c3601d00.k8s.civo.com
    http:
      paths:
      - backend:
          service:
            name: helloservice
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - demo.e65f444e-e201-40bd-b0f4-7a18c3601d00.k8s.civo.com
    secretName: demo
